ALTER TABLE persons
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;


ALTER TABLE employees
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE users
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;